import type { Category, Item, User } from "./types"

export const categories: Category[] = [
  { slug: "textbooks", name: "教材书籍", icon: "BookOpen", count: 128 },
  { slug: "electronics", name: "电子产品", icon: "Laptop", count: 256 },
  { slug: "furniture", name: "家具生活", icon: "Armchair", count: 89 },
  { slug: "clothing", name: "服装配饰", icon: "Shirt", count: 167 },
  { slug: "transport", name: "交通工具", icon: "Bike", count: 45 },
]

export const users: User[] = [
  {
    id: "u1",
    name: "张小明",
    avatar: "",
    school: "UCLA",
    rating: 4.8,
    itemsCount: 12,
    joinedDate: "2024-09-01",
  },
  {
    id: "u2",
    name: "李思琪",
    avatar: "",
    school: "USC",
    rating: 4.9,
    itemsCount: 8,
    joinedDate: "2024-08-15",
  },
  {
    id: "u3",
    name: "王大卫",
    avatar: "",
    school: "NYU",
    rating: 4.7,
    itemsCount: 15,
    joinedDate: "2024-07-20",
  },
  {
    id: "u4",
    name: "陈美玲",
    avatar: "",
    school: "Columbia",
    rating: 5.0,
    itemsCount: 6,
    joinedDate: "2024-10-01",
  },
  {
    id: "u5",
    name: "赵天宇",
    avatar: "",
    school: "UC Berkeley",
    rating: 4.6,
    itemsCount: 20,
    joinedDate: "2024-06-01",
  },
  {
    id: "u6",
    name: "刘雨萱",
    avatar: "",
    school: "Boston University",
    rating: 4.8,
    itemsCount: 9,
    joinedDate: "2024-09-15",
  },
]

export const currentUser: User = {
  id: "u0",
  name: "林小鱼",
  avatar: "",
  school: "Stanford University",
  rating: 4.9,
  itemsCount: 5,
  joinedDate: "2024-08-01",
}

export const items: Item[] = [
  {
    id: "item-1",
    title: "微积分教材 第八版",
    description: "James Stewart 的 Calculus Early Transcendentals 第八版，保存完好，只有少量铅笔标注，可擦除。适合大一大二微积分课程使用。",
    price: 35,
    originalPrice: 120,
    images: ["/images/items/textbook-1.jpg"],
    category: "textbooks",
    condition: "轻微使用",
    deliveryMethod: "均可",
    seller: users[0],
    location: "Los Angeles, CA",
    createdAt: "2025-02-15",
    isFavorited: false,
    viewCount: 234,
    distance: "500m",
  },
  {
    id: "item-2",
    title: "MacBook Pro 14寸 M3 芯片",
    description: "2024款 MacBook Pro 14寸，M3芯片，16GB内存，512GB SSD。购买不到一年，电池循环次数不到100。带原装充电器和包装盒。因为换了新款所以出售。",
    price: 1200,
    originalPrice: 1999,
    images: ["/images/items/laptop-1.jpg"],
    category: "electronics",
    condition: "仅拆封",
    deliveryMethod: "自取",
    seller: users[1],
    location: "Los Angeles, CA",
    createdAt: "2025-02-14",
    isFavorited: true,
    viewCount: 567,
    distance: "1.2km",
  },
  {
    id: "item-3",
    title: "IKEA 书桌 MALM 系列",
    description: "IKEA MALM 书桌，白色，140x65cm。使用一年，状态良好，桌面有几处轻微划痕。毕业搬家，急出！可帮忙拆卸。",
    price: 45,
    originalPrice: 179,
    images: ["/images/items/desk-1.jpg"],
    category: "furniture",
    condition: "轻微使用",
    deliveryMethod: "自取",
    seller: users[2],
    location: "New York, NY",
    createdAt: "2025-02-13",
    isFavorited: false,
    viewCount: 189,
    distance: "2.5km",
  },
  {
    id: "item-4",
    title: "Sony WH-1000XM5 降噪耳机",
    description: "Sony旗舰降噪耳机，黑色。音质超棒，降噪效果一流。因为换了AirPods Max所以出。配件齐全，有原装收纳盒。",
    price: 180,
    originalPrice: 399,
    images: ["/images/items/headphones-1.jpg"],
    category: "electronics",
    condition: "全新",
    deliveryMethod: "均可",
    seller: users[3],
    location: "New York, NY",
    createdAt: "2025-02-12",
    isFavorited: false,
    viewCount: 345,
    distance: "800m",
  },
  {
    id: "item-5",
    title: "捷安特城市自行车",
    description: "Giant Escape 3 城市通勤自行车，蓝色，M码。骑了两个学期，定期保养，变速顺畅。含车锁和前后灯。适合校园通勤。",
    price: 150,
    originalPrice: 450,
    images: ["/images/items/bike-1.jpg"],
    category: "transport",
    condition: "轻微使用",
    deliveryMethod: "自取",
    seller: users[4],
    location: "Berkeley, CA",
    createdAt: "2025-02-11",
    isFavorited: false,
    viewCount: 278,
    distance: "3.1km",
  },
  {
    id: "item-6",
    title: "Canada Goose 羽绒服 女款",
    description: "加拿大鹅 Shelburne Parka，黑色，S码。去年冬天买的，只穿了一个冬天。保暖效果非常好，适合东北部的冬天。",
    price: 450,
    originalPrice: 1050,
    images: ["/images/items/jacket-1.jpg"],
    category: "clothing",
    condition: "轻微使用",
    deliveryMethod: "均可",
    seller: users[5],
    location: "Boston, MA",
    createdAt: "2025-02-10",
    isFavorited: true,
    viewCount: 412,
    distance: "5.8km",
  },
  {
    id: "item-7",
    title: "iPad Pro 12.9寸 + Apple Pencil",
    description: "iPad Pro 2022款，12.9寸，256GB，WiFi版。搭配第二代Apple Pencil一起出。非常适合上课记笔记和画画。屏幕贴了类纸膜。",
    price: 650,
    originalPrice: 1299,
    images: ["/images/items/ipad-1.jpg"],
    category: "electronics",
    condition: "轻微使用",
    deliveryMethod: "均可",
    seller: users[0],
    location: "Los Angeles, CA",
    createdAt: "2025-02-09",
    isFavorited: false,
    viewCount: 489,
    distance: "350m",
  },
  {
    id: "item-8",
    title: "象印电饭煲 5.5杯",
    description: "Zojirushi NS-TSC10 电饭煲，5.5杯容量。煮饭超好吃，有多种模式。使用一年半，功能完全正常。附带原装蒸笼和量杯。",
    price: 65,
    originalPrice: 180,
    images: ["/images/items/ricecooker-1.jpg"],
    category: "furniture",
    condition: "轻微使用",
    deliveryMethod: "自取",
    seller: users[2],
    location: "New York, NY",
    createdAt: "2025-02-08",
    isFavorited: false,
    viewCount: 156,
    distance: "1.8km",
  },
  {
    id: "item-9",
    title: "Herman Miller Aeron 人体工学椅",
    description: "Herman Miller Aeron人体工学椅，B号（中码）。坐着超舒服，对腰特别好。买来写论文用的，现在毕业了带不走。",
    price: 380,
    originalPrice: 1395,
    images: ["/images/items/chair-1.jpg"],
    category: "furniture",
    condition: "轻微使用",
    deliveryMethod: "自取",
    seller: users[4],
    location: "Berkeley, CA",
    createdAt: "2025-02-07",
    isFavorited: false,
    viewCount: 367,
    distance: "4.2km",
  },
  {
    id: "item-10",
    title: "电动滑板 Boosted Mini",
    description: "Boosted Mini S 电动滑板，续航约11公里。上课代步神器！电池状态良好，附带充电器和备用轮子。",
    price: 220,
    originalPrice: 749,
    images: ["/images/items/skateboard-1.jpg"],
    category: "transport",
    condition: "明显使用",
    deliveryMethod: "自取",
    seller: users[3],
    location: "New York, NY",
    createdAt: "2025-02-06",
    isFavorited: false,
    viewCount: 198,
    distance: "2.0km",
  },
  {
    id: "item-11",
    title: "Nike Air Force 1 白色 42码",
    description: "Nike AF1经典白色，42码（US 8.5）。穿了几次，鞋底几乎没有磨损。因为买大了所以出，鞋型很正。",
    price: 55,
    originalPrice: 110,
    images: ["/images/items/sneakers-1.jpg"],
    category: "clothing",
    condition: "全新",
    deliveryMethod: "均可",
    seller: users[1],
    location: "Los Angeles, CA",
    createdAt: "2025-02-05",
    isFavorited: false,
    viewCount: 223,
    distance: "600m",
  },
  {
    id: "item-12",
    title: "Fjallraven Kanken 双肩包",
    description: "北极狐经典款双肩包，深蓝色。容量刚好适合日常上课使用，防水面料。只背了一个学期，几乎没有使用痕迹。",
    price: 40,
    originalPrice: 80,
    images: ["/images/items/backpack-1.jpg"],
    category: "clothing",
    condition: "仅拆封",
    deliveryMethod: "均可",
    seller: users[5],
    location: "Boston, MA",
    createdAt: "2025-02-04",
    isFavorited: false,
    viewCount: 167,
    distance: "7.5km",
  },
]

export function getItemsByCategory(slug: string): Item[] {
  return items.filter((item) => item.category === slug)
}

export function getItemById(id: string): Item | undefined {
  return items.find((item) => item.id === id)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((cat) => cat.slug === slug)
}

export function searchItems(query: string): Item[] {
  const q = query.toLowerCase()
  return items.filter(
    (item) =>
      item.title.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q)
  )
}
